/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface XCMBridgeInterface extends Interface {
  getFunction(
    nameOrSignature: "estimateFee" | "getSupportedChains" | "owner" | "transfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeEstimated" | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "estimateFee",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedChains",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "estimateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace FeeEstimatedEvent {
  export type InputTuple = [
    destinationParaId: BigNumberish,
    refTime: BigNumberish,
    proofSize: BigNumberish,
    feePas: BigNumberish
  ];
  export type OutputTuple = [
    destinationParaId: bigint,
    refTime: bigint,
    proofSize: bigint,
    feePas: bigint
  ];
  export interface OutputObject {
    destinationParaId: bigint;
    refTime: bigint;
    proofSize: bigint;
    feePas: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    sender: AddressLike,
    destinationParaId: BigNumberish,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    destinationParaId: bigint,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    sender: string;
    destinationParaId: bigint;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XCMBridge extends BaseContract {
  connect(runner?: ContractRunner | null): XCMBridge;
  waitForDeployment(): Promise<this>;

  interface: XCMBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  estimateFee: TypedContractMethod<
    [destinationParaId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        refTime: bigint;
        proofSize: bigint;
        feePas: bigint;
      }
    ],
    "view"
  >;

  getSupportedChains: TypedContractMethod<[], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  transfer: TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "estimateFee"
  ): TypedContractMethod<
    [destinationParaId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        refTime: bigint;
        proofSize: bigint;
        feePas: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedChains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeeEstimated"
  ): TypedContractEvent<
    FeeEstimatedEvent.InputTuple,
    FeeEstimatedEvent.OutputTuple,
    FeeEstimatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "FeeEstimated(uint32,uint64,uint64,uint256)": TypedContractEvent<
      FeeEstimatedEvent.InputTuple,
      FeeEstimatedEvent.OutputTuple,
      FeeEstimatedEvent.OutputObject
    >;
    FeeEstimated: TypedContractEvent<
      FeeEstimatedEvent.InputTuple,
      FeeEstimatedEvent.OutputTuple,
      FeeEstimatedEvent.OutputObject
    >;

    "TransferInitiated(address,uint32,address,address,uint256)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
