/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface XCMKitInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "XCMMessageSent" | "XCMTransferInitiated"
  ): EventFragment;
}

export namespace XCMMessageSentEvent {
  export type InputTuple = [messageId: BytesLike, destination: BytesLike];
  export type OutputTuple = [messageId: string, destination: string];
  export interface OutputObject {
    messageId: string;
    destination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMTransferInitiatedEvent {
  export type InputTuple = [
    destinationParaId: BigNumberish,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    destinationParaId: bigint,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    destinationParaId: bigint;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XCMKit extends BaseContract {
  connect(runner?: ContractRunner | null): XCMKit;
  waitForDeployment(): Promise<this>;

  interface: XCMKitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "XCMMessageSent"
  ): TypedContractEvent<
    XCMMessageSentEvent.InputTuple,
    XCMMessageSentEvent.OutputTuple,
    XCMMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "XCMTransferInitiated"
  ): TypedContractEvent<
    XCMTransferInitiatedEvent.InputTuple,
    XCMTransferInitiatedEvent.OutputTuple,
    XCMTransferInitiatedEvent.OutputObject
  >;

  filters: {
    "XCMMessageSent(bytes32,bytes32)": TypedContractEvent<
      XCMMessageSentEvent.InputTuple,
      XCMMessageSentEvent.OutputTuple,
      XCMMessageSentEvent.OutputObject
    >;
    XCMMessageSent: TypedContractEvent<
      XCMMessageSentEvent.InputTuple,
      XCMMessageSentEvent.OutputTuple,
      XCMMessageSentEvent.OutputObject
    >;

    "XCMTransferInitiated(uint32,address,address,uint256)": TypedContractEvent<
      XCMTransferInitiatedEvent.InputTuple,
      XCMTransferInitiatedEvent.OutputTuple,
      XCMTransferInitiatedEvent.OutputObject
    >;
    XCMTransferInitiated: TypedContractEvent<
      XCMTransferInitiatedEvent.InputTuple,
      XCMTransferInitiatedEvent.OutputTuple,
      XCMTransferInitiatedEvent.OutputObject
    >;
  };
}
