/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiLocationTest__factory } from "./MultiLocationTest__factory";
export { ScaleEncoderTest__factory } from "./ScaleEncoderTest__factory";
export { XCMProgramTest__factory } from "./XCMProgramTest__factory";
