/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiLocationTest } from "./MultiLocationTest";
export type { ScaleEncoderTest } from "./ScaleEncoderTest";
export type { XCMProgramTest } from "./XCMProgramTest";
