/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MultiLocationTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACALA"
      | "ASSET_HUB"
      | "ASTAR"
      | "BIFROST"
      | "BRIDGE_HUB"
      | "HYDRATION"
      | "MOONBEAM"
      | "testAccountId32"
      | "testAccountKey20"
      | "testAssetById"
      | "testAssetLocation"
      | "testNativeAsset"
      | "testParachain"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ACALA", values?: undefined): string;
  encodeFunctionData(functionFragment: "ASSET_HUB", values?: undefined): string;
  encodeFunctionData(functionFragment: "ASTAR", values?: undefined): string;
  encodeFunctionData(functionFragment: "BIFROST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "HYDRATION", values?: undefined): string;
  encodeFunctionData(functionFragment: "MOONBEAM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testAccountId32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testAccountKey20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testAssetById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testAssetLocation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testNativeAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testParachain",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ACALA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ASSET_HUB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ASTAR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BIFROST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "HYDRATION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MOONBEAM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testAccountId32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAccountKey20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAssetById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testAssetLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testNativeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testParachain",
    data: BytesLike
  ): Result;
}

export interface MultiLocationTest extends BaseContract {
  connect(runner?: ContractRunner | null): MultiLocationTest;
  waitForDeployment(): Promise<this>;

  interface: MultiLocationTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACALA: TypedContractMethod<[], [bigint], "view">;

  ASSET_HUB: TypedContractMethod<[], [bigint], "view">;

  ASTAR: TypedContractMethod<[], [bigint], "view">;

  BIFROST: TypedContractMethod<[], [bigint], "view">;

  BRIDGE_HUB: TypedContractMethod<[], [bigint], "view">;

  HYDRATION: TypedContractMethod<[], [bigint], "view">;

  MOONBEAM: TypedContractMethod<[], [bigint], "view">;

  testAccountId32: TypedContractMethod<
    [accountId: BytesLike],
    [string],
    "view"
  >;

  testAccountKey20: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  testAssetById: TypedContractMethod<[assetId: BigNumberish], [string], "view">;

  testAssetLocation: TypedContractMethod<
    [token: AddressLike],
    [string],
    "view"
  >;

  testNativeAsset: TypedContractMethod<[], [string], "view">;

  testParachain: TypedContractMethod<[paraId: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACALA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ASSET_HUB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ASTAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BIFROST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BRIDGE_HUB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HYDRATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MOONBEAM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "testAccountId32"
  ): TypedContractMethod<[accountId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "testAccountKey20"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "testAssetById"
  ): TypedContractMethod<[assetId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "testAssetLocation"
  ): TypedContractMethod<[token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "testNativeAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "testParachain"
  ): TypedContractMethod<[paraId: BigNumberish], [string], "view">;

  filters: {};
}
