/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ScaleEncoderTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "testConcat"
      | "testEncodeBytes"
      | "testEncodeCompact"
      | "testEncodeMultiLocation"
      | "testEncodeString"
      | "testEncodeU128"
      | "testEncodeU32"
      | "testEncodeU64"
      | "testEncodeU8"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "testConcat",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeCompact",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeMultiLocation",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeU128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeU32",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeU64",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testEncodeU8",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "testConcat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeCompact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeMultiLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeU128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeU32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeU64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testEncodeU8",
    data: BytesLike
  ): Result;
}

export interface ScaleEncoderTest extends BaseContract {
  connect(runner?: ContractRunner | null): ScaleEncoderTest;
  waitForDeployment(): Promise<this>;

  interface: ScaleEncoderTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  testConcat: TypedContractMethod<[parts: BytesLike[]], [string], "view">;

  testEncodeBytes: TypedContractMethod<[data: BytesLike], [string], "view">;

  testEncodeCompact: TypedContractMethod<
    [value: BigNumberish],
    [string],
    "view"
  >;

  testEncodeMultiLocation: TypedContractMethod<
    [parents: BigNumberish, interior: BytesLike],
    [string],
    "view"
  >;

  testEncodeString: TypedContractMethod<[str: string], [string], "view">;

  testEncodeU128: TypedContractMethod<[value: BigNumberish], [string], "view">;

  testEncodeU32: TypedContractMethod<[value: BigNumberish], [string], "view">;

  testEncodeU64: TypedContractMethod<[value: BigNumberish], [string], "view">;

  testEncodeU8: TypedContractMethod<[value: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "testConcat"
  ): TypedContractMethod<[parts: BytesLike[]], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeBytes"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeCompact"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeMultiLocation"
  ): TypedContractMethod<
    [parents: BigNumberish, interior: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "testEncodeString"
  ): TypedContractMethod<[str: string], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeU128"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeU32"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeU64"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "testEncodeU8"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;

  filters: {};
}
