/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface XCMProgramTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "testBuildReserveTransfer"
      | "testBuildTeleport"
      | "testBuyExecution"
      | "testClearOrigin"
      | "testDepositAsset"
      | "testWithdrawAsset"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "testBuildReserveTransfer",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testBuildTeleport",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testBuyExecution",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testClearOrigin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testDepositAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testWithdrawAsset",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "testBuildReserveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBuildTeleport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBuyExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testClearOrigin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testDepositAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testWithdrawAsset",
    data: BytesLike
  ): Result;
}

export interface XCMProgramTest extends BaseContract {
  connect(runner?: ContractRunner | null): XCMProgramTest;
  waitForDeployment(): Promise<this>;

  interface: XCMProgramTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  testBuildReserveTransfer: TypedContractMethod<
    [
      assetLocation: BytesLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      beneficiary: BytesLike
    ],
    [string],
    "view"
  >;

  testBuildTeleport: TypedContractMethod<
    [
      assetLocation: BytesLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      beneficiary: BytesLike
    ],
    [string],
    "view"
  >;

  testBuyExecution: TypedContractMethod<
    [assetLocation: BytesLike, feeAmount: BigNumberish],
    [string],
    "view"
  >;

  testClearOrigin: TypedContractMethod<[], [string], "view">;

  testDepositAsset: TypedContractMethod<
    [beneficiary: BytesLike],
    [string],
    "view"
  >;

  testWithdrawAsset: TypedContractMethod<
    [assetLocation: BytesLike, amount: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "testBuildReserveTransfer"
  ): TypedContractMethod<
    [
      assetLocation: BytesLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      beneficiary: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "testBuildTeleport"
  ): TypedContractMethod<
    [
      assetLocation: BytesLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      beneficiary: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "testBuyExecution"
  ): TypedContractMethod<
    [assetLocation: BytesLike, feeAmount: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "testClearOrigin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "testDepositAsset"
  ): TypedContractMethod<[beneficiary: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "testWithdrawAsset"
  ): TypedContractMethod<
    [assetLocation: BytesLike, amount: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
